name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: macos-latest
    #strategy:
     # matrix:
       # xcode: ['/Applications/Xcode_11.2.1.app/Contents/Developer']
    
    
    steps:
    #checkout源码
    - name: Checkout
      uses: actions/checkout@v1
    #前往主要目录下
    - name: to project dir
      run: |
          cd testGit
          ls
          pod install
          fastlane archive_ipa
