name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: ['/Applications/Xcode_11.2.1.app/Contents/Developer']
    
    
    steps:
    #checkout源码
    - name: Checkout
      uses: actions/checkout@v1
    #前往主要目录下
    - name: cd testGit
      run: cd testGit
    #安装pod
    - name: install pod
      run: pod install
