name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ['/Applications/Xcode_11.2.1.app/Contents/Developer']
    
    
    steps:
    #checkout源码
    - name: Checkout
      uses: actions/checkout@v1
    #前往主要目录下
    - name: to project dir
      run: |
          cd testGit
          ls
          bundle exec pod install
          bundle exec fastlane archive_ipa
      env:
        DEVELOPER_DIR: ${{ matrix.xcode }}
